### Trigonometric Functions

In [3]:
import numpy as np

In [4]:
arr1 = np.arange(1,13).reshape(4,3)
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
np.sin(arr1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292]])

In [6]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396]])

In [7]:
np.tan(arr1)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01],
       [ 8.71447983e-01, -6.79971146e+00, -4.52315659e-01],
       [ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01]])

### Dot Product

In [8]:
print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
arr2 = np.arange(12,24).reshape(3,4)
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
np.dot(arr1,arr2)

array([[104, 110, 116, 122],
       [248, 263, 278, 293],
       [392, 416, 440, 464],
       [536, 569, 602, 635]])

### Log and Exponents

In [14]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

### Round, floor and ceil

In [21]:
arr3 = np.array([1.8,1.2,2.9,2.2,4.5])

In [22]:
# Round - Rounds off the elements of an array to the nearest integer
rounded_arr3 = np.round(arr3)
print(rounded_arr3)

# Note that 4.5 is rounded off to 4

[2. 1. 3. 2. 4.]


In [23]:
# Round to two decimals

arr4 = np.array([1.812,21.132,2.911,2.2474,4.5100])
rounded_arr4 = np.round(arr4,2)
print(rounded_arr4)

[ 1.81 21.13  2.91  2.25  4.51]


In [27]:
np.round(np.random.random((2,3))*100)

array([[63.,  5., 68.],
       [42., 63., 41.]])

In [28]:
np.random.random((2,3))*100

array([[89.80999012, 63.22804891, 66.17489778],
       [96.25252371, 23.30658826, 23.22599526]])

In [31]:
# Floor

arr4

array([ 1.812 , 21.132 ,  2.911 ,  2.2474,  4.51  ])

In [32]:
np.floor(arr4)

array([ 1., 21.,  2.,  2.,  4.])

In [ ]:
# Ceil

In [33]:
np.ceil(arr4)

array([ 2., 22.,  3.,  3.,  5.])

### Iterating

In [40]:
arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# Looping over a 1D array
for i in arr5:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [42]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
# Looping over a 2D array
for i in arr1:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [49]:
# Looping over a 2D array
arr6 = np.arange(12).reshape(2,2,3)
for i in arr6:
    print(i)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [50]:
# Using nditer
for i in np.nditer(arr6):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### Reshaping

### Transpose

In [52]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
np.transpose(arr1)

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [54]:
# Another way to transpose
arr1.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [55]:
arr6

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [56]:
arr6.T

array([[[ 0,  6],
        [ 3,  9]],

       [[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]]])

### Ravel
    Converting any dimensions to 1D

In [57]:
arr6

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [58]:
arr6.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Stacking
    For joining multiple arrays having the same number of rows/columns

In [69]:
arr7 = np.arange(1,19).reshape(3,6)
arr8 = np.arange(20,38).reshape(6,3)
arr9 = np.arange(1,13).reshape(3,4)
arr10 = np.arange(13,25).reshape(4,3)
print(arr7)
print(arr8)
print(arr9)
print(arr10)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]


In [70]:
# Horizontal Stacking
np.hstack((arr7,arr9))

array([[ 1,  2,  3,  4,  5,  6,  1,  2,  3,  4],
       [ 7,  8,  9, 10, 11, 12,  5,  6,  7,  8],
       [13, 14, 15, 16, 17, 18,  9, 10, 11, 12]])

In [71]:
np.hstack((arr7,arr10))
# Note the error - hstack needs to contain the same number of rows

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4

In [74]:
np.vstack((arr8,arr10))
# vstack needs to contain the same number of columns

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

### Splitting
    It's the opposite of stacking

In [75]:
arr7

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [76]:
np.hsplit(arr7,2)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18]])]

In [78]:
np.vsplit(arr8,2)

[array([[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]),
 array([[29, 30, 31],
        [32, 33, 34],
        [35, 36, 37]])]

In [81]:
np.vsplit(arr8,3)

[array([[20, 21, 22],
        [23, 24, 25]]),
 array([[26, 27, 28],
        [29, 30, 31]]),
 array([[32, 33, 34],
        [35, 36, 37]])]

### NumPy Arrays vs Python Lists
NumPy arrays have a fixed size unlike Python lists that grow dynamically
When the size of an ndarray is changed, what actually happens is that a new array is created and the original one is deleted

#### Comparing the speed

In [82]:
# List uses element-wise addition
import time

a = [i for i in range(1,1000000)]
b = [i for i in range(1000001,2000000)]
c = []

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time() - start)

0.373457670211792


In [83]:
# Numpy
import numpy as np
a = np.arange(1,1000000)
b = np.arange(1000001,2000000)

start = time.time()
c = a + b
print(time.time() - start)

0.04500865936279297


**Note** - Here we can cleary observe that NumPy is faster than lists.

#### Memory Used

In [84]:
# List
a

array([     1,      2,      3, ..., 999997, 999998, 999999])

In [86]:
import sys
a = [i for i in range(1,1000000)]
sys.getsizeof(a)

8448728

In [87]:
# NumPy
a = np.arange(1,1000000)
sys.getsizeof(a)

4000100