# Math
- In-built module used for mathematical tasks

**Function vs Module vs Package**
  - Module - collection of functions
  - Package - collection of modules

In [2]:
x = sqrt(25)
# Note that we get an error since math has not been imported

NameError: name 'sqrt' is not defined

In [6]:
import math
x = math.sqrt(25)
x

5.0

In [4]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
      

In [11]:
math.sqrt(15)

3.872983346207417

In [12]:
math.floor(3.87)

3

In [13]:
math.ceil(3.87)

4

In [14]:
math.pow(3,2)

9.0

In [16]:
print(math.pi)

3.141592653589793


In [17]:
print(math.e)

2.718281828459045


In [18]:
m.sqrt(25)
# this does not work since aliasing has not been done

NameError: name 'm' is not defined

In [19]:
import math as m
m.sqrt(25)

5.0

In [20]:
from math import sqrt, pow, ceil, floor
# Note: importing many functions at the same time saves memory

print(pow(2,3))
print(sqrt(25))
print(ceil(3.7))
print(floor(3.7))

8.0
5.0
4
3


In [22]:
from math import sqrt as s, pow as p, ceil as c, floor as f
# Note: functions can also be aliased

print(p(2,3))
print(s(25))
print(c(3.7))
print(f(3.7))

8.0
5.0
4
3


In [23]:
s(25)

5.0

In [24]:
from math import *
# imports all the 30 functions in math module

In [25]:
s(25)

5.0

In [26]:
sqrt(25)

5.0

In [27]:
x = input()
# By default input function reads only a string

sr


In [29]:
type(x)

str

In [30]:
x1 = input()

3


In [31]:
x2 = input()

4


In [34]:
print(x1 + x2)
# since by default, it is a string
print(type(x1))
print(type(x2))

34
<class 'str'>
<class 'str'>


In [33]:
int(x1) + int(x2)
# Typecasting

7

In [38]:
a1 = int(input('Enter the first number: '))
b1 = int(input('Enter the second number: '))
print('Sum is:',a1 + b1)

Enter the first number: 20
Enter the second number: 30
Sum is: 50


In [39]:
x = input('Enter a character: ')

Enter a character: Srujana


In [40]:
# For taking input in char format
x = input('Enter a character: ')
x[0]

Enter a character: hello


'h'

In [43]:
result = eval(input('Print expression that needs to be evaluated: '))
result

Print expression that needs to be evaluated: 1+10*100


1001

# NumPy 
  - Numerical Python
  - N Dimensional array

In [49]:
!pip install numpy
# You do not need to install this, if anaconda has been installed

In [50]:
import numpy as np

In [51]:
np.__version__
# package.__version__

'1.21.5'

In [80]:
np.array([1,553,3,46,3,15]) # 1D Array

array([  1, 553,   3,  46,   3,  15])

In [81]:
l1 = [0,1,2,3,4,5]    # Vector
arr = np.array(l1)
print(arr)

[0 1 2 3 4 5]


In [82]:
type(arr)

numpy.ndarray

In [83]:
# 2D Array
arr2 = np.array([[4,21,5,6],[25,74,9,34,3]])
print(arr2)

[list([4, 21, 5, 6]) list([25, 74, 9, 34, 3])]


C:\Users\sruja\AppData\Local\Temp\ipykernel_29256\4082904293.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2 = np.array([[4,21,5,6],[25,74,9,34,3]])


### dtype
  Desired data type of the array

In [84]:
np.array([33,52,73], dtype = float)

array([33., 52., 73.])

In [85]:
np.array([33,52,73], dtype = complex)

array([33.+0.j, 52.+0.j, 73.+0.j])

In [53]:
print(l1)
print(type(l1))
print(arr)
print(type(arr))

[0, 1, 2, 3, 4, 5]
<class 'list'>
[0 1 2 3 4 5]
<class 'numpy.ndarray'>


### arange

In [55]:
np.arange(15)
# int

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
np.arange(3.0)
# float

array([0., 1., 2.])

In [57]:
np.arange(4)
# Single argument

array([0, 1, 2, 3])

In [59]:
np.arange(0,4)
# Two arguments

array([0, 1, 2, 3])

In [58]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [60]:
np.arange(20,10)
# First argument should be less than second argument

array([], dtype=int32)

In [62]:
np.arange(-10,10)
# Negative argument

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [63]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [64]:
ar = np.arange(-20,-10)
ar

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [65]:
np.arange(10,10)

array([], dtype=int32)

In [66]:
np.arange()
# Atleast one argument is required

TypeError: arange() requires stop to be specified.

In [67]:
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [68]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [69]:
np.arange(1,15,3,8)
# Note the error, max three arguments an be passed

TypeError: Cannot interpret '8' as a data type

### zeros

In [70]:
np.zeros(3)

array([0., 0., 0.])

In [71]:
np.zeros(5,dtype = int)
# using the concept of hyper parameter tuning

array([0, 0, 0, 0, 0])

In [73]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

   NumPy vs PyTorch
   - Numpy - Array
   - PyTorch - Tensor (Python + Torch), Torch is installed

In [74]:
n = (6,7)
np.zeros(n)
# Passing a variable

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

### ones

In [75]:
np.ones(3)

array([1., 1., 1.])

In [76]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [79]:
print(n)
np.ones(n)

(6, 7)


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

### reshape
Pre-requisite - both the number products must be equal to the number of items present inside the array

In [87]:
np.arange(1,9).reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [88]:
np.arange(1,9).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### linspace
  - Linearly spaced
  - Creates points at equal distance

In [91]:
np.linspace(1,10,10)  # lower range, upper range (both inclusive), number of items to generate

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### identity
 - Diagonal elements are 1, remaining 0

In [92]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [93]:
a1 = np.arange(5)                                #1D - Array
a1

array([0, 1, 2, 3, 4])

In [95]:
a2 = np.arange(12, dtype = float).reshape(2,6)   #2D - Matrix 
a2

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [98]:
a3 = np.arange(12).reshape(2,2,3)                #3D - Tensor
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### Summary
- import math
- import math as m (aliasing)
- math has 30 functions in total
- math.sqrt()
- math.floor()
- math.ceil()
- math.pow(a,b)
- math.pi
- math.e
- importing module, importing 1 to all functions
- 35 keywords in python. Keyword - import
- install vscode and pycharm
- input(), taking user input, typecasting to int, getting a single character
- input() with number, string with index
- eval(input()) - for evaluating user entered expressions
- \*  shows when kernel is still running
- executing a program using python filename from the command prompt
- streamlit - to create an app